#!/usr/bin/env bash
# Generates wrapper translation units for vendored C code. Re-run after any submodule bump.
# Each wrapper #includes one upstream .c file, so SwiftPM compiles upstream sources from our
# own target directories without modifying the submodules.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PKG="$ROOT/SeleniteKit"
MBED_SRC="$PKG/Vendor/mbedtls/library"
MBED_OUT="$PKG/Sources/MbedCrypto"

rm -f "$MBED_OUT"/mbed_*.c
for f in "$MBED_SRC"/*.c; do
  name="$(basename "$f")"
  printf '// Generated by Scripts/gen-vendor-wrappers.sh. Do not edit.\n#include "../../Vendor/mbedtls/library/%s"\n' "$name" > "$MBED_OUT/mbed_$name"
done
echo "mbedTLS wrappers: $(ls "$MBED_OUT"/mbed_*.c | wc -l | tr -d ' ')"

MLC="$PKG/Vendor/moonlight-common-c"
SDK="$(xcrun --sdk appletvos --show-sdk-path)"
TRIPLE="arm64-apple-tvos26.0"
DEFS=(-DNDEBUG -DHAS_SOCKLEN_T -D__APPLE_USE_RFC_3542 -DHAS_FCNTL=1 -DHAS_IOCTL=1 -DHAS_POLL=1
      -DHAS_GETADDRINFO=1 -DHAS_GETNAMEINFO=1 -DHAS_INET_PTON=1 -DHAS_INET_NTOP=1 -DHAS_MSGHDR_FLAGS=1
      -DUSE_MBEDTLS -DMBEDTLS_THREADING_C -DMBEDTLS_THREADING_PTHREAD)
INCS=(-I"$MLC/enet/include" -I"$MLC/nanors" -I"$MLC/nanors/deps" -I"$MLC/nanors/deps/obl"
      -I"$PKG/Vendor/mbedtls/include")

# upstream path relative to the package root, and the wrapper file name
slot_sources() {
  for f in "$MLC"/src/*.c; do n="$(basename "$f")"; echo "Vendor/moonlight-common-c/src/$n mlc_$n"; done
  for n in callbacks compress host list packet peer protocol unix; do
    echo "Vendor/moonlight-common-c/enet/$n.c enet_$n.c"
  done
  echo "Vendor/moonlight-common-c/nanors/rs.c nanors_rs.c"
  echo "Vendor/moonlight-common-c/nanors/deps/obl/oblas_common.c obl_oblas_common.c"
  echo "Vendor/moonlight-common-c/nanors/deps/obl/oblas_lite.c obl_oblas_lite.c"
}

# Collect every external symbol the upstream code defines, compiled for the real target.
OBJ="$(mktemp -d)"
trap 'rm -rf "$OBJ"' EXIT
while read -r rel wrapper; do
  xcrun clang -target "$TRIPLE" -isysroot "$SDK" -std=c11 -O0 -w "${DEFS[@]}" "${INCS[@]}" \
    -c "$PKG/$rel" -o "$OBJ/$wrapper.o"
done < <(slot_sources)
SYMBOLS="$(nm -g -U -j "$OBJ"/*.o | grep -v ':$' | grep -v '^$' | sed 's/^_//' | sort -u)"

for SLOT in A B; do
  OUT="$PKG/Sources/MoonlightSlot$SLOT"
  mkdir -p "$OUT"
  rm -f "$OUT"/mlc_*.c "$OUT"/enet_*.c "$OUT"/nanors_*.c "$OUT"/obl_*.c
  {
    echo "// Generated by Scripts/gen-vendor-wrappers.sh. Do not edit."
    echo "// Renames every external symbol of this moonlight-common-c copy to Slot${SLOT}_*."
    echo "#pragma once"
    while read -r sym; do echo "#define $sym Slot${SLOT}_$sym"; done <<< "$SYMBOLS"
  } > "$OUT/SlotPrefix.h"
  while read -r rel wrapper; do
    printf '// Generated by Scripts/gen-vendor-wrappers.sh. Do not edit.\n#include "SlotPrefix.h"\n#include "../../%s"\n' "$rel" > "$OUT/$wrapper"
  done < <(slot_sources)
done
echo "slot symbols: $(echo "$SYMBOLS" | wc -l | tr -d ' ')"
