#!/usr/bin/env bash
# Generates wrapper translation units for vendored C code. Re-run after any submodule bump.
# Each wrapper #includes one upstream .c file, so SwiftPM compiles upstream sources from our
# own target directories without modifying the submodules.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PKG="$ROOT/SeleniteKit"
MBED_SRC="$PKG/Vendor/mbedtls/library"
MBED_OUT="$PKG/Sources/MbedCrypto"

rm -f "$MBED_OUT"/mbed_*.c
for f in "$MBED_SRC"/*.c; do
  name="$(basename "$f")"
  printf '// Generated by Scripts/gen-vendor-wrappers.sh. Do not edit.\n#include "../../Vendor/mbedtls/library/%s"\n' "$name" > "$MBED_OUT/mbed_$name"
done
echo "mbedTLS wrappers: $(ls "$MBED_OUT"/mbed_*.c | wc -l | tr -d ' ')"
